version: "3.7"

services:
  resa-backend:
    container_name: resa-backend
    build: .
    ports:
      - "8080:8080"
    restart: always
    networks:
      - resa_net
    depends_on:
      - resa-liquibase

  resa-db:
    container_name: resa-db
    image: postgres:14
    networks:
      - resa_net
    ports:
      - "5432:5432"
    volumes:
      - resa-db:/var/lib/postgresql/data
      - ./db/resa-db/conf/postgres.conf:/etc/postgresql/postgresql.conf:ro
    env_file:
      - ./db/resa-db/.env
    restart: always
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      

  resa-liquibase:
    image: liquibase/liquibase:4.2.0
    container_name: resa-liquibase
    env_file:
      - ./db/db-dataloader/.env
    volumes:
      - ./db/db-dataloader/resources/changelog:/liquibase/changelog
      - ./db/db-dataloader/resources/migrations:/liquibase/migrations
      - ./db/db-dataloader/liquibase_policy_init.sh:/liquibase/liquibase_policy_init.sh:ro
      - ./db/db-dataloader/wait-for-it.sh:/liquibase/wait-for-it.sh
    entrypoint: ./liquibase_policy_init.sh
    networks:
      - resa_net
    depends_on:
      - resa-db

networks:
  resa_net:
    name: resa_net

volumes:
  resa-db:
    name: resa-db
