global:
  scrape_interval: 2s
  scrape_timeout: 1s

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - "alerting:9093"

scrape_configs:
  - job_name: "Prometheus"
    metrics_path: "/metrics"
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    static_configs:
    - targets:
      - "prometheus:9090"
      labels:
        group: "Prometheus"
    
  - job_name: "Backend"
    metrics_path: "/api/actuator/prometheus"
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    static_configs:
      - targets:
        - "frontend"
        labels:
          group: "Backend"

  - job_name: "Postgres"
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "postgres_exporter:9187"
        labels:
          group: "Database"
  
  - job_name: "resa-backend"
    metrics_path: "/api/actuator/prometheus"
    static_configs:
      - targets:
        - "resa-backend:8080"
        labels:
          group: "Backend"