groups:
- name: AllInstances
  rules:
  - alert: "InstanceDown"
    # Condition for alerting
    expr: up == 0
    for: 30s
    # Annotation - additional informational labels to store more information
    annotations:
      title: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 seconds."
    # Labels - additional labels to be attached to the alert
    labels:
      severity: "Critical"